### ISSUE TITLE
whois.wildwestdomains.com parser (GH-271) breaks functionality

### ISSUE THREAD

**Issue by scarver2** [weppos/whois#282]
v3.4.1 breaks the `.registrar` and `.expires_on` methods when pulling records from whois.wildwestdomains.com. They are both returning `nil`.

`Whois.whois('a1webconsulting.com').registrar` should return
=> #<struct Whois::Record::Registrar
 id=nil,
 name="WILD WEST DOMAINS, LLC",
 organization="WILD WEST DOMAINS, LLC",
 url="http://www.wildwestdomains.com">

`Whois.whois('a1webconsulting.com').expires_on` should return
=> 2014-02-13 00:00:00 -0600

**Comment by weppos** [comment]
`whois.wildwestdomains.com` was updated on #462.

**Comment by scarver2** [comment]
Thank you. Confirmed that parsing is working with multiple Wild West Domains.
