### ISSUE TITLE
False positive available domain [whois.rrpproxy.net]

### ISSUE THREAD

**Issue by thomasguillory** [weppos/whois#295]
I'm testing the availability of `syxf.com`

The domain is currently at status `redemptionPeriod` and so **not available**

However `Whois.whois('syxf.com').available?` is returning `true`

I think this is because the whois response is incorrect : last line is `not found...` and      [the parser](https://github.com/weppos/whois/blob/master/lib/whois/record/scanners/base_shared3.rb#L33-L35) use that indication to return available status.

    >> whois syxf.com
    Whois Server Version 2.0
    
    Domain names in the .com and .net domains can now be registered
    with many different competing registrars. Go to http://www.internic.net
    for detailed information.
    
       Domain Name: SYXF.COM
       Registrar: KEY-SYSTEMS GMBH
       Whois Server: whois.rrpproxy.net
       Referral URL: http://www.key-systems.net
       Name Server: NS2.EXPIRATIONWARNING.NET
       Name Server: NS6.EXPIRATIONWARNING.NET
       Status: redemptionPeriod
       Updated Date: 22-dec-2013
       Creation Date: 09-nov-2007
       Expiration Date: 09-nov-2013
    
    >>> Last update of whois database: Sun, 12 Jan 2014 17:47:20 UTC <<<
    
    NOTICE: [...]
    
    TERMS OF USE: [...]

    not found...

**Comment by weppos** [comment]
Closing as this is a very old topic and the parsers have been moved to https://github.com/weppos/whois-parser
