### ISSUE TITLE
False positive available domain [whois.networksolutions.com]

### ISSUE THREAD

**Issue by thomasguillory** [weppos/whois#296]
Same issue that [#295](https://github.com/weppos/whois/issues/295) on another whois server.

I'm testing the availability of `bvkt.com`

The domain is currently at status `redemptionPeriod` and so **not available**

However `Whois.whois('bvkt.com').available?` is returning `true`

I think this is because the whois response is incorrect : last line is `No match for "BVKT.COM".`

    >> whois bvkt.com    
    Whois Server Version 2.0
    
    Domain names in the .com and .net domains can now be registered
    with many different competing registrars. Go to http://www.internic.net
    for detailed information.
    
       Domain Name: BVKT.COM
       Registrar: NETWORK SOLUTIONS, LLC.
       Whois Server: whois.networksolutions.com
       Referral URL: http://www.networksolutions.com/en_US/
       Name Server: NS1.PENDINGRENEWALDELETION.COM
       Name Server: NS2.PENDINGRENEWALDELETION.COM
       Status: redemptionPeriod
       Updated Date: 19-dec-2013
       Creation Date: 07-nov-1997
       Expiration Date: 06-nov-2013
    
    >>> Last update of whois database: Sun, 12 Jan 2014 18:07:58 UTC <<<
    
    NOTICE: [...]
    
    TERMS OF USE: [...]
    
    No match for "BVKT.COM".

**Comment by weppos** [comment]
Closing as this is a very old topic and the parsers have been moved to https://github.com/weppos/whois-parser
