### ISSUE TITLE
Change behaviour of getting properties in parser

### ISSUE THREAD

**Issue by huyphan** [weppos/whois#322]
I'm looking at this piece of code in `lib/whois/record/parser.rb`

``` ruby
      def delegate_property_to_parsers(method, *args, &block)
        if parsers.empty?
          raise ParserError, "Unable to select a parser because the Record is empty"
        elsif (prop = select_parser { |p| p.class.property_state?(method, PROPERTY_STATE_SUPPORTED) })
          parser.send(method, *args, &block)
        elsif (parser = select_parser { |p| p.class.property_state?(method, PROPERTY_STATE_NOT_SUPPORTED) })
          parser.send(method, *args, &block)
        else
          raise AttributeNotImplemented, "Unable to find a parser for property `#{method}'"
        end
      end

      def delegate_method_to_parsers(method, *args, &block)
        if parsers.empty?
          raise ParserError, "Unable to select a parser because the Record is empty"
        elsif (parser = select_parser { |p| p.respond_to?(method) })
          parser.send(method, *args, &block)
        else
          nil
        end
      end
```

It's a bit inconsitent for me where it's returning `nil` if the method is not available in any parser whilst it's raising error when looking for a property.

There's also a problem with `delegate_property_to_parsers` where it only use the first parser that supports the given property. Let's say there are two parsers corresponding to two parts, both support that property but the first parser returns `nil` for some reason and the second one returns valid information, we would endup having `nil` value for that property. 

So I suggest that we simplify the `delegate_property_to_parsers` function like this:

``` ruby
      def delegate_property_to_parsers(method, *args, &block)
        if parsers.empty?
          raise ParserError, "Unable to select a parser because the Record is empty"
        else
          parsers.each do |parser|
            prop = parser.send(method, *args, &block) if parser.class.property_state?(method, PROPERTY_STATE_SUPPORTED) || parser.class.property_state?(method, PROPERTY_STATE_NOT_SUPPORTED)
            return prop if prop
          end
          nil
        end
      end
```

Need to know your opinion on this before I submit a pull request (or you can use that code directly if you are happy with it)

**Comment by weppos** [comment]
@huyphan FYI I moved the parser component to https://github.com/weppos/whois-parser. I also changed the default behavior of the parser/record to raise in case of not-implemented and not-supported properties (see https://github.com/weppos/whois-parser/pull/5).

I'm still working to finalize the migration to the `whois-parser` gem. Once this is completed, I'd like to revisit also your idea of the smart parser (https://github.com/weppos/whois/pull/312).
