### ISSUE TITLE
Whois::Record for TLD .fr

### ISSUE THREAD

**Issue by ex0s** [weppos/whois#351]
Hi there, i've been trying a few JSON queries from the whois ruby app and i've noticed domains with the french TLD (.fr) are missing a few things. I am pretty sure about this since the plain text response provides many more details and other properties not supported/updated.

So heres a text file with some examples i did from the RoboWhois API to illustrate this, but i had identical results on my app that's only using the whois gem.

https://www.dropbox.com/s/jchu7o7pc4yvcsx/issue_parser.docx?dl=0

Most notably, here are the main differences between plain text and JSON version : 

- Disclaimer, domain Name and ID
- Registrar
- In Whois::Record::Contact type (admin_contacts, registrant_contacts, technical_contacts), properties name, city, zip, state and country.

Thanks.

**Comment by weppos** [comment]
Closing as this is a very old topic and the parsers have been moved to https://github.com/weppos/whois-parser
