### ISSUE TITLE
Support for property delete_on

### ISSUE THREAD

**Issue by troelskn** [weppos/whois#381]
Some whois gives a delete date (dk-hostmaster for example), which denotes when an expired domain is dropped. I currently have the following monkey patch to add the support, but perhaps it would be worthwhile to add the property support to the main framework? I'll be happy to supply a PR.

```
require 'whois'
# Note: Must be included before the rest of ruby-whois
Whois::Record::Parser::PROPERTIES << :delete_on

require 'whois/record/parser/whois.dk-hostmaster.dk'
Whois::Record::Parser::WhoisDkHostmasterDk.class_eval do
  property_supported :delete_on do
    if content_for_scanner =~ /Delete date:\s+(.*)\n/
      Time.parse($1)
    end
  end
end
```

**Comment by weppos** [comment]
Closing as this is a very old topic and the parsers have been moved to https://github.com/weppos/whois-parser
