### ISSUE TITLE
GoDaddy throttling

### ISSUE THREAD

**Issue by feens** [weppos/whois#393]
I've noticed that GoDaddy throttles requests, but the parser has no support for it.  Thus far I've added this method to extend the parser:

        def response_throttled?
          !!(content_for_scanner =~ /For complete domain details go to/)
        end

**Comment by weppos** [comment]
That is not a throttled response, rather a partial response. The way GoDaddy throttles requests is by dropping the socket connection.

**Comment by feens** [comment]
So what's the proper way of handling this then?

**Comment by weppos** [comment]
There was some discussion to improve the ability to deal with separate parts in a thin request flow (#186), but it was never implemented.

**Comment by feens** [comment]
Also...would that method be valid if changed to response_incomplete?

**Comment by weppos** [comment]
Not really. `response_incomplete` was designed to deal with a partial response, generally caused by a network issue. In this case, it's just a limited content (some registrars limit content based on the number of requests to avoid data abuse). The response itself it's still formally valid and complete.

**Comment by feens** [comment]
It may be valid, but at least in the case, if I try and query expires_on, I get nil, even though if I'm looking at the text whois, there is an expires_on provided.  Maybe the issue isn't in the part-parser itself then, but that how it's decided on which part-parser to use.

**Comment by weppos** [comment]
It should be falling back to the parent parser, if the specific one doesn't contain the value.

**Comment by feens** [comment]
well, in this case, there's 2 parts: the version part, and the godaddy part.  By 'parent parser' do you mean another part-parser, or parsers/base?
