### ISSUE TITLE
Don't use part-parsers that are throttled?

### ISSUE THREAD

**Issue by feens** [weppos/whois#394]
When dealing with GoDaddy throttling, I noticed that even if the part-parser will return true for throttling, the record-parser will use it as a source for properties.  I.e. The main version parser has a valid expiry date, but the godaddy parser does not, and if I query expires_on, it returns nil, as it is using the godaddy parser. For now I've just patched ours to not use throttled parsers in select_parser, but I wonder if this should be an option?

```
class Parser

  def select_parser(&block)
    parsers.each do |parser|
      return parser if !parser.try(:response_throttled?) && block.call(parser)
    end
    nil
  end

end
```

**Comment by feens** [comment]
As per discussion on #393, I guess "throttled" should perhaps be "incomplete" in this case.

**Comment by weppos** [comment]
Parser support moved to https://github.com/weppos/whois-parser

This issue will soon be obsolete as .COM is moving towards thick whois in 2018.
