### ISSUE TITLE
How to check if a domain.ltda is available?

### ISSUE THREAD

**Issue by luccascm** [weppos/whois#400]
I need to check if a domain with .ltda extension is available... I've tried to check like this:
w = Whois::Client.new
w.lookup("google.com").available? => false
w.lookup("google.ltda").available? => nil

w.lookup("lhpoijklk.com").available? => true
w.lookup("lhpoijklk.ltda").available? => true

Is there any difference on checking .ltda domains? Or is it a bug on 'available?' return?

**Comment by weppos** [comment]
The `ltda` uses the `whois.afilias-srs.net` whois server. The library doesn't currently have any parser for such server, therefore the response is not consistent.

I would not consider it a bug, rather an incomplete implementation. I should probably raise an exception in this case.

**Comment by luccascm** [comment]
Got it. Thanks for the reply.
Can you suggest me some way of checking a .ltda domain via JSON? I'm working on a Rails project that checks if a full domain is available to register and I got stucked when dealing with .ltda extensions. =/
Raising and exception is not a good option for me, I really need to check it

**Comment by weppos** [comment]
The exception part was referred to this library. If you need to check it, you can implement a parser following the example of the other existing parsers. Feel free to submit a PR with the parser if you want it to be included in the lib.
