### ISSUE TITLE
whois.domain-registry.nl Throttle message

### ISSUE THREAD

**Issue by maxok** [weppos/whois#401]
There is new message whois.domain-registry.nl returns for maximum number of requests per minute exceeded. At the moment whois library is considering the domain to be available in this case, which is incorrect. Following should be added to the response_throttled? method in whois/lib/whois/record/parser/whois.domain-registry.nl.rb:

when /^#{Regexp.escape("whois.domain-registry.nl: maximum number of requests per minute exceeded")}/
            true

**Comment by weppos** [comment]
@maxok Can you provide a full response? Ideally, the output of the whois server stored in a file.

    $ whoisrb whatever.nl > file.txt

**Comment by weppos** [comment]
Closing as no-followups, and because parsers are now in a separate repository.
