### ISSUE TITLE
Inaccurate method name Whois::Record#technical in the document

### ISSUE THREAD

**Issue by niku4i** [weppos/whois#406]
In http://whoisrb.org/, the following example is written:

```
t = r.technical
# => #<Whois::Record::Contact ...>
```

but this raises an exception like `NoMethodError: undefined method technical for #<Whois::Record:0x007f91730e2f98>`.  `t = r.technical_contact` must be correct.

**Comment by weppos** [comment]
Yes, it looks like the documentation is wrong.

**Comment by weppos** [comment]
I fixed the documentation, thank you.
