### ISSUE TITLE
Parsing .cr or .es websites

### ISSUE THREAD

**Issue by songm5178** [weppos/whois#409]
Hi,
I am new using your whois parser, so I don't know if this is the right place to tell you bugs or questions, but here is a problem that I have been running into.

I cannot seem to get the parser to parse .es and .cr websites. For example, "elpais.es" and "kat.cr" both have whois information if I search them through the internet but they do not seem to be able to get parsed.. Will this be fixed anytime soon?

Thanks!

**Comment by weppos** [comment]
Both .CR and .ES don't provide any official whois server accessible via whois protocol. The only way to access the details is via web, using their web whois interfaces.

For this reason, it's not possible to use this library to fetch the whois record for .CR or .ES domains.
