### ISSUE TITLE
Parser error with .tn domains

### ISSUE THREAD

**Issue by skelkelos** [weppos/whois#416]
The following error is generated:

Unexpected token: This is JWhoisServer serving ccTLD tn;تونس
Java Whois Server 0.4.1.2    (c) 2006 - 2014 Klaus Zerwes zero-sys.net
All rights reserved.
Copyright "Tunisian Internet Agency - http://whois.tn"

NO OBJECT FOUND!

**Comment by skelkelos** [comment]
this issue applies to both .tn and all .tn subdomains

**Comment by weppos** [comment]
Parsers moved to https://github.com/weppos/whois-parser/
