### ISSUE TITLE
Parser error with .tc domains

### ISSUE THREAD

**Issue by skelkelos** [weppos/whois#417]
The following unexpected token is reported:

Unexpected token: The data in the WHOIS database of NIC TC Registry LTD is provided by NIC TC Registry LTD for information purposes, and to assist persons in obtaining information about or related to domain name registration records. NIC TC Registry LTD does not guarantee its accuracy.By submitting a WHOIS query, you agree that you will use this data only for lawful purposes and that, under no circumstances, you will use this data to
1) allow, enable, or otherwise support the transmission of mass unsolicited, commercial advertising or solicitations via E-mail (spam)
or
2) enable high volume, automated, electronic processes that apply to NIC TC Registry LTD or its systems.
NIC TC Registry LTD reserves the right to modify these terms.
By submitting this query, you agree to abide by this policy.

&gt;&gt;&gt; Last update of WHOIS database: 2015-07-20T05:32:00.711Z &lt;&lt;&lt;

**Comment by weppos** [comment]
@skelkelos can you provide a domain name that returned this error?

**Comment by skelkelos** [comment]
Here you are: google.tc

Whois::ParserError(Unexpected token: The data in the WHOIS database of NIC TC Registry LTD is provided by NIC TC Registry LTD for information purposes, and to assist persons in obtaining information about or related to domain name registration records. NIC TC Registry LTD does not guarantee its accuracy.By submitting a WHOIS query, you agree that you will use this data only for lawful purposes and that, under no circumstances, you will use this data to 1) allow, enable, or otherwise support the transmission of mass unsolicited, commercial advertising or solicitations via E-mail (spam) or 2) enable high volume, automated, electronic processes that apply to NIC TC Registry LTD or its systems. NIC TC Registry LTD reserves the right to modify these terms. By submitting this query, you agree to abide by this policy. >>> Last update of WHOIS database: 2015-11-30T12:44:13.314Z <<<)

**Comment by weppos** [comment]
Thanks!

**Comment by weppos** [comment]
I didn't realize it was for a `.tc`, despite it was written in clear letters. Sorry.

**Comment by skelkelos** [comment]
No problem at all! Cheers

**Comment by weppos** [comment]
Parsers moved to https://github.com/weppos/whois-parser/
