### ISSUE TITLE
Issue with .IN domains (Unexpected token)

### ISSUE THREAD

**Issue by skelkelos** [weppos/whois#423]
tested with microsoft.in

Unexpected token: Access to .IN WHOIS information is provided to assist persons in determining the contents of a domain name registration record in the .IN registry database. The data in this record is provided by .IN Registry for informational purposes only, and .IN does not guarantee its accuracy. This service is intended only for query-based access. You agree that you will use this data only for lawful purposes and that, under no circumstances will you use this data to(a) allow, enable, or otherwise support the transmission by e-mail, telephone, or facsimile of mass unsolicited, commercial advertising or solicitations to entities other than the data recipient's own existing customers; or (b) enable high volume, automated, electronic processes that send queries or data to the systems of Registry Operator, a Registrar, or Afilias except as reasonably necessary to register domain names or modify existing registrations. All rights reserved. .IN reserves the right to modify these terms at any time. By submitting this query, you agree to abide by this policy.

**Comment by weppos** [comment]
Closed in 821cf41ab264fb116ec25521affe7df09a12d666. See c43ae7b and GH-438.
