### ISSUE TITLE
UTF-8 decode issue with .HU domains

### ISSUE THREAD

**Issue by skelkelos** [weppos/whois#426]
UnicodeDecodeError('utf8', '% Whois server 2.08d serving the hu ccTLD\r
\r
domain: microsoft.hu\r
record created: 1997.04.08 00:37:10\r
Tov\xe1bbi adatok\xe9rt ld.:\r
http://www.domain.hu/domain/domainsearch/\r
For further data see:\r
http://www.domain.hu/domain/English/domainsearch/\r
\r
', 131, 132, 'invalid continuation byte')

**Comment by weppos** [comment]
Duplicates #11
