### ISSUE TITLE
Add support for additional gTLDs

### ISSUE THREAD

**Issue by skelkelos** [weppos/whois#429]
bet	whois.afilias.net
game	whois.uniregistry.net
srl	whois.afilias-srs.net

**Comment by weppos** [comment]
I update the list of new gTLDs as frequently as I can, following the updates (and generally the order) posted at https://github.com/whois/ianawhois. Unfortunately, ICANN is approving new gTLD with a very high frequency and it's hard to stay behind all the changes.

Feel free to provide a patch.
