### ISSUE TITLE
Parser can't detect throttling message

### ISSUE THREAD

**Issue by skelkelos** [weppos/whois#435]
1) Unexpected token: Your request could not be performed.

This happens with .ms, .gl, .iq, .mg

2) Unexpected token: Your request could not be performed - lookup quota exceeded.

This happens with .mu

3) Unexpected token: Lookup quota exceeded.

This happens with .bi

4) Unexpected token: Your request could not be performed. Lookup quota may be exceeded.

This happens with .na

**Comment by skelkelos** [comment]
This also happens with some whois servers for .com & .net resulting in "Unexpected token: Excessive use"

**Comment by weppos** [comment]
Parser support moved to https://github.com/weppos/whois-parser
