### ISSUE TITLE
Outsource the whois server list.

### ISSUE THREAD

**Issue by malkusch** [weppos/whois#439]
Hi

I see that there are a handful of projects which do maintain their own individual whois server list. How about combining those lists into one single place and just maintain that together?

I created https://github.com/whois-server-list/whois-server-list where you can find a XML list containing top level domains from IANA plus its whois servers. The schema can be changed within a new major versions.

Also I'd like to use this opportunity to ask you if I may incorporate your list. I use the WTFL license.

**Comment by weppos** [comment]
Hi @malkusch, I currently manually update the list according to the updates posted at https://github.com/whois/ianawhois. At the time being, I'm not considering to replace the list with something maintained elsewhere as the process of changing a TLD server requires updates on the parsers as well.

Feel free reuse the list, as long as it's clear (as it seems to be) that this project is currently under the MIT license.
