### ISSUE TITLE
Support for parsing .tech domains?

### ISSUE THREAD

**Issue by mattbrictson** [weppos/whois#441]
Using whois 3.6.2, looking up a `.tech` domain results in a `Blank` parser that gives no data:

```ruby
record = Whois.whois("outoftheboxit.tech")
record.expires_on # => nil
record.registrar # => nil
record.parser.parsers.map(&:class) # => [Whois::Record::Parser::Blank]
```

Looking at the `tld.json` file, I find:

```json
".tech": {
    "host": "whois.nic.tech"
  }
```

But there is no corresponding `whois.ic.tech.rb` parser for this host. Maybe I am missing something here, but how is this supposed to work if there is no parser registered for the `.tech` tld?

*Edit: Am I correct in assuming that the whois gem currently does not have parsing support for `.tech` domains? If so, then consider this a feature request, not a bug.*

**Comment by weppos** [comment]
That's correct, the Blank parser is returned when no parser is found. Most
of the new gTLDs have no parser. ICANN is approving so many new gTLDs
that's impossible for me to say ahead of it.

On Tue, Sep 15, 2015 at 12:07 AM, Matt Brictson <notifications@github.com>
wrote:

> Using whois 3.6.2, looking up a .tech domain results in a Blank parser
> that gives no data:
>
> record = Whois.whois("outoftheboxit.tech")
> record.expires_on # => nil
> record.registrar # => nil
> record.parser.parsers.map(&:class) # => [Whois::Record::Parser::Blank]
>
> Looking at the tld.json file, I find:
>
> ".tech": {
>     "host": "whois.nic.tech"
>   }
>
> But there is no corresponding whois.ic.tech.rb parser for this host.
> Maybe I am missing something here, but how is this supposed to work if
> there is no parser registered for the .tech tld?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/weppos/whois/issues/441>.
>



-- 
Simone Carletti
Passionate programmer and dive instructor

http://simonecarletti.com/
Twitter: @weppos <https://twitter.com/weppos>

**Comment by skelkelos** [comment]
Parser for .tech (and a lot more new gTLDs) is the same of whois.centralnic.com

**Comment by weppos** [comment]
I know, but it still takes time to:

1. generate a proper fixture
2. write the appropriate specs
3. validate the responses

At the time being, as my time is limited, I'm focusing my energies on trying to keep the definition of TLDs up to date.

Feel free to provide a patch.
