### ISSUE TITLE
Incorrect expected value in the spec of whois.co.ug

### ISSUE THREAD

**Issue by huyphan** [weppos/whois#442]
`whois.co.ug` uses EAT timezone for updated time, this can be seen in `spec/fixtures/responses/whois.co.ug/status_registered.txt`:

```
Nameserver:         ns3.cfi.co.ug
MNT-BY:             MAINT-UG
Source:             UG
Updated:            10/11/2009 14:06:58 EAT
```

However UTC is used in `spec/fixtures/responses/whois.co.ug/status_registered.expected` which is incorrect.

```
#updated_on
  %s %CLASS{time}
  %s %TIME{2009-11-10 14:06:58 UTC}
```

I think the date time parser of Ruby was failed to recognise EAT timezone, and the author of that `whois.co.ug` parser decided to workaround with the spec instead of solving the parsing issue.

**Comment by weppos** [comment]
> I think the date time parser of Ruby was failed to recognise EAT timezone, and the author of that whois.co.ug parser decided to workaround with the spec instead of solving the parsing issue.

This is definitely possible. Another option is that for some reason I didn't notice that at the time I wrote the parser.

Feel free to provide a patch.

**Comment by weppos** [comment]
Whois parsers are now defined in a separate gem.
https://github.com/weppos/whois-parser
