### ISSUE TITLE
whois.ripe.net is not the WHOIS server for .gm

### ISSUE THREAD

**Issue by martin-schmidt** [weppos/whois#454]
whois.ripe.net is not the WHOIS server for .gm (Gambia). .gm has no whois server, but the whois database can be accessed at http://www.nic.gm/htmlpages/whois.htm

**Comment by weppos** [comment]
Hi @martin-schmidt, as far as I can see that's what it is contained in the definition.
https://github.com/weppos/whois/blob/master/data/tld.json#L523-L527

Are you experiencing any issue?

**Comment by martin-schmidt** [comment]
@weppos I found while writing tests:
https://github.com/weppos/whois/tree/master/spec/fixtures/responses/whois.ripe.net/gm

**Comment by weppos** [comment]
You are right. I updated the definition a long time ago in https://github.com/weppos/whois/commit/04b145dddba49550f56d40bc04acd2ce398d1dcf, but apparently I never removed the folder with the specs.
