### ISSUE TITLE
False positive for some .no domains

### ISSUE THREAD

**Issue by lauritzsh** [weppos/whois#456]
Hi, I have been experiencing false positives for some .no domains, saying they are available when they are not.

For example localhost.no:

```
$ whois localhost.no
% Kopibeskyttet, se http://www.norid.no/domenenavnbaser/whois/kopirett.html
% Rights restricted by copyright. See http://www.norid.no/domenenavnbaser/whois/kopirett.en.html

% No match
```

It is "kopibeskyttet" or "copy protected", so it's not available for anyone. Could the .no parser look for this **Kopibeskyttet** word explicitly or do you handle edge-cases differently?

Could it be done like this?

``` ruby
property_supported :available? do
  return false if !!(content_for_scanner =~ /^% Kopibeskyttet/)
  !!(content_for_scanner =~ /^% No match/)
end
```

**Comment by lauritzsh** [comment]
I have opened a pull request if the solution is okay, I'm not sure if you prefer to handle it in a different way. The pull request is #457.

**Comment by lauritzsh** [comment]
I was too quick to open an issue, I can see "Kopibeskyttet" for any query, whether it's taken or not. It does say `% No match` for localhost.no still, but it seems to be taken: https://www.norid.no/en/?query=localhost.no.

I assume this problem is out of the scope for Ruby whois though, so it can be closed if it's not possible to determine whether for example localhost.no is taken or not.

**Comment by weppos** [comment]
Parsers moved to https://github.com/weppos/whois-parser/
