### ISSUE TITLE
Mention utils/mkwhois.rb in CONTRIBUTING.md

### ISSUE THREAD

**Issue by mpchadwick** [weppos/whois#461]
`mkwhois.rb` is a nice time saving script for writing tests for a parser, but there's no mention of it in `CONTRIBUTING.md`. Do you think it's worth adding a note on its usage to that document?

**Comment by weppos** [comment]
@mpchadwick that's definitely a good idea. However, I'm planning to split the parser from the main whois repo. Would you mind to propose the patch at https://github.com/weppos/whois-parser instead of in this repo?

**Comment by weppos** [comment]
Also, is Domain Clamp still a thing? If you're still actively working on the project, I'd like to chat with you. Feel free to drop me a line at the email address attached to my account. :)
