### ISSUE TITLE
Parser for whois-cl01.mm-registry.com, whois-dub.mm-registry.com and whois-lon.mm-registry.com

### ISSUE THREAD

**Issue by skelkelos** [weppos/whois#466]
Can you please add parser for Minds+Machine registry

**Comment by weppos** [comment]
I'm closing this ticket as parsers have been moved to https://github.com/weppos/whois-parser. 

At the time being, I can't accept feature requests for the parsers as there are several missing parsers. Feel free to provide a patch with the parsers.
