### ISSUE TITLE
Parser error with some com/net domains managed by resellers

### ISSUE THREAD

**Issue by skelkelos** [weppos/whois#473]
1) Unexpected token: Utrdba d.o.o.

For testing: utrdba.com

2) Unexpected token: ThaHosting - Webhosting vanaf 1 euro per maand

For testing: youritemsonline.com

3) Unexpected token: Please register your domains at; www.hostio.nl; This data is provided by Hostio Solutions

For testing: hostio-review.com

4) Unexpected token: DunaNet Domain Services

For testing: optimallwebshop.com

5) Unexpected token: Domain registered to Behostings. Shared hosting, dedicated servers, virtual servers for all your needs! http://www.behostings.be/ 

For testing: renauddejeneffe.com

6) Unexpected token: De Krachtcentrale BV www.dekrachtcentrale.nl

For testing: astroverde.com

7) Unexpected token: Manifesto for Agile Software Development We are uncovering better ways of developing software by doing it and helping others do it. Through this work we have come to value: Individuals and interactions over processes and tools Working software over comprehensive documentation Customer collaboration over contract negotiation Responding to change over following a plan That is, while there is value in the items on the right, we value the items on the left more.

For testing: auxeq.com

8) Unexpected token: **---** _\- _--______ **--( / \ )XXXXXXXXXXXXX_ --XXX( O O )XXXXXXXXXXXXXXX- /XXX( U ) XXXXXXX\ /XXXXX( )--_ XXXXXXXXXXX\ /XXXXX/ ( O ) XXXXXX \XXXXX\ XXXXX/ / XXXXXX \** \XXXXX---- XXXXXX__/ XXXXXX __---- - ---___ XXX__/ XXXXXX __ --- -- --**/ ___/\ XXXXXX / ___---= -_ ___/ XXXXXX '--- XXXXXX --\/XXX\ XXXXXX /XXXXX \XXXXXXXXX /XXXXX/ \XXXXXX _/XXXXX/ \XXXXX--**/ __-- XXXX/ --XXXXXXX--------------- XXXXX-- \XXXXXXXXXXXXXXXXXXXXXXXX- --XXXXXXXXXXXXXXXXXX-

For testing: fadichehade.com

**Comment by weppos** [comment]
Parsers moved to https://github.com/weppos/whois-parser/
