### ISSUE TITLE
Missing whois servers

### ISSUE THREAD

**Issue by skelkelos** [weppos/whois#475]
Find below a list of TLDs with missing whois server but supported according to changelog

realtor
xn--ses554g
pharmacy
xbox
xn--45q11c
bloomberg
williamhill
microsoft

**Comment by weppos** [comment]
All the TLDs listed above are currently listed in the definition file.
https://github.com/weppos/whois/blob/master/data/tld.json

**Comment by skelkelos** [comment]
They are listed, but whois server is missing, therefore "This 'tld' has no whois server" error is generated. Whois server should be added to definition file.

**Comment by weppos** [comment]
The server is missing because the registry hasn't made it available yet.

See for example https://github.com/whois/ianawhois/blob/master/REALTOR There is no whois server defined for it.
