### ISSUE TITLE
Parser error with GoDaddy

### ISSUE THREAD

**Issue by skelkelos** [weppos/whois#477]
Unknown registrar format `GoDaddy.com, LLC' Please report the issue at http://github.com/weppos/whois/issues

For testing: 0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0.info

**Comment by weppos** [comment]
Duplicate of https://github.com/weppos/whois/issues/481
