### ISSUE TITLE
Unknown registrar format

### ISSUE THREAD

**Issue by toxzic** [weppos/whois#491]
> whois.rb -d kijureayujoqof.info

C:/Ruby22/lib/ruby/gems/2.2.0/gems/whois-3.6.2/lib/whois.rb:138:in `bug!': Unknown registrar format `Soluciones Corporativas IP, SLU' Please report the issue at http://github.com/weppos/whois/issues (Whois::ParserError)

**Comment by weppos** [comment]
Please upgrade to the latest whois version.

**Comment by toxzic** [comment]
Thanks!
