### ISSUE TITLE
Where are the parsers?

### ISSUE THREAD

**Issue by monkeysuffrage** [weppos/whois#509]
I need to fix parsing for some common registrars but I can't because the parsers aren't in the repo.

**Comment by weppos** [comment]
Parsers have been moved to https://github.com/weppos/whois-parser

In the new versions, the parsers will be published as a separate gem.

**Comment by monkeysuffrage** [comment]
So there's no way to push fixes?

**Comment by weppos** [comment]
Yes. Simply provide a pull-request against the new repository.

**Comment by monkeysuffrage** [comment]
Sorry, I don't get it, the current gem doesn't use that code. Am I missing
something?

**Comment by weppos** [comment]
No, the current gem doesn't use that code. But if you fix it in the repo I mentioned, it will be published in the next release.

In any case, even if the parser would be in this repo, you would have to wait a new release to be able to use the changes.

**Comment by monkeysuffrage** [comment]
Ok. I'd like to contribute but it's too complicated at the moment. What's
the ETA on the next release?.

**Comment by weppos** [comment]
I already released a beta. I expect to release the final version by the end of this month.
