### ISSUE TITLE
When using available?

### ISSUE THREAD

**Issue by kaesaeki** [weppos/whois#510]
I have a question about using available?.

If the response is true does that mean the domain is available for registration?

I am finding that in most cases the domain is already registered or has been for a few months.

**Comment by weppos** [comment]
This seems like a bug. Can you give me one or two domains where you are experiencing this behavior?

**Comment by kaesaeki** [comment]
These domains are not available for registration

`Whois.whois("www.idii.com").available?`
`=> true`
`Whois.whois("www.idii.com").registered?`
 `=> false`
`Whois.whois("www.orghelp.com").available?`
`=> true`
`Whois.whois("www.orghelp.com").registered?`
 `=> false`

**Comment by weppos** [comment]
Those are not domains, because you prepended `www`. `www.idii.com` is a subdomain, `idii.com` is the domain.
