### ISSUE TITLE
available? in 4.x?

### ISSUE THREAD

**Issue by marcandre** [weppos/whois#515]
The README of the `beta1` still says that one can:

    r = Whois.whois("google.it")
    # => #<Whois::Record>

    r.available?

But I get a `NoMethodError`... What's the deal? (Spec commented out in 3bd5cc6f2b64b)

**Comment by weppos** [comment]
Hi @marcandre, thanks for the report. For 4.x, I moved the parsers outside the main repo. I need to make sure this method is available only when the parser dependency is loaded (as it requires the parsers).

I'm fixing the latest things before the release. I'll double check this issue. Thanks for reporting it.
