### ISSUE TITLE
Issues parsing corporatedomains.com response

### ISSUE THREAD

**Issue by bhazard** [weppos/whois#520]
Looks as if cd may have changed format.  I am getting nil for expires_on for this domain (as well as a few other fields).  3.6.5 as well as 4.0.
Is whois.corporatedomains.com.rb the correct place for a 3.6 patch?  I can do this and submit a pull request if helpful.  Not sure where parser is for 4.0.

**Comment by weppos** [comment]
Whois parsers are now defined in a separate gem.
https://github.com/weppos/whois-parser

Do you mind to report the issue in the new repository?
