### ISSUE TITLE
.fi domain available? returns Whois::ParserError: Unexpected token: Nameservers

### ISSUE THREAD

**Issue by maxok** [weppos/whois#530]
I have tried to conduct whois on .fi domain and whois worked fine, but whenever I tried to parse whois record, I receved: Whois::ParserError: Unexpected token: Nameservers

Example:

`r = Whois.whois("google.fi")`
`r.available?`

Same goes with methods: registered? and created_on?

**Comment by weppos** [comment]
Whois parsers are now defined in a separate gem.
https://github.com/weppos/whois-parser

Do you mind to report the issue in the new repository?
