### ISSUE TITLE
doc: v4 upgrade link broken

### ISSUE THREAD

**Issue by tuxayo** [weppos/whois#544]
In this page
http://www.rubydoc.info/gems/whois

The link in the text
"If you are upgrading to 4.0, see 4.0-Upgrade.md."

Is broken.

**Comment by weppos** [comment]
It looks like RubyDoc.info doesn't properly understand links. In fact, even the CHANGELOG.md link is broken.

You can read the original README [here](https://github.com/weppos/whois), this is the link to the upgrade documentation file: https://github.com/weppos/whois/blob/master/4.0-Upgrade.md

**Comment by tuxayo** [comment]
I found something in the RubyDocs doc. https://rubydoc.tenderapp.com/kb/frequently-asked-questions/broken-links-404-to-markdown-or-text-documents#how-to-report-broken-links-to-library-authors

It's seems that there is no way to support relative links in markdown. Are you okay with using absolute links? I could do a PR to use links that point to RubyDocs or GitHub depending of what you want.

**Comment by weppos** [comment]
So far, the only affected system I know is RubyDoc.info. In GitHub and other places it works fine. Therefore, I'm inclined to not change it.

**Comment by tuxayo** [comment]
Good, thanks for your quick answers and this great gem!
