### ISSUE TITLE
Parsing raw text containing whois info

### ISSUE THREAD

**Issue by ciokan** [weppos/whois#546]
Is there any way in which this library could be used to parse existing records/without performing any lookup to the whois servers? I'm asking because I need to parse a huge number of such records and this is the only library that I found to output a lot of useful stuff.

Unfortunately I don't know Ruby that much, I looked at the code without being able to figure out how to use just the parser and give it a string -> output.

I would highly appreciate a bit of example.

**Comment by ciokan** [comment]
Ok I thought I figured it out but it's incomplete. While this works:

`puts Whois.whois('stripe.com').parser.registrant_contacts`

This doesn't:
```
part = Whois::Record::Part.new(body: File.read("stripe.txt"))# file contains full whois response
server = Whois::Server.guess('stripe.com')
parser = Whois::Parser.parser_klass(server.host)

res = parser.new(part)
puts res.registrant_contacts
```

Failing with:

```
/var/lib/gems/2.3.0/gems/whois-parser-1.0.0/lib/whois/parsers/base.rb:105:in `_property_registrant_contacts': Whois::AttributeNotImplemented (Whois::AttributeNotImplemented)
	from /var/lib/gems/2.3.0/gems/whois-parser-1.0.0/lib/whois/parsers/base.rb:393:in `handle_property'
	from /var/lib/gems/2.3.0/gems/whois-parser-1.0.0/lib/whois/parsers/base.rb:240:in `registrant_contacts'
	from test.rb:30:in `<main>'
```

I haven't done any ruby before but, from the looks of it, parser base has no such attributes. But why is it using the base parser..no idea. If I call `puts parser` it says `Whois::Parsers::WhoisVerisignGrsCom`

Any help is much appreciated.

**Comment by weppos** [comment]
What you should do is to use a `Whois::Record`:

```ruby
p = [Whois::Record::Part.new(body: File.read("stripe.txt"), host: "...")]
r = Whois::Record.new(nil, p)

parser = Whois::Parser.new(r)
parser.registrant_contacts
```

One important caveats: .COM is a thin WHOIS system, hence you generally have at least 2 parts: the first part is verisign, the second one is the final registry. You need to provide these parts separately (the `host` value attached to each part represents the server that returned that part

**Comment by ciokan** [comment]
Yeah I noticed that the buffer was spitting two parts when debugging it. I think I learned ruby last night with this package. Thank you
