### ISSUE TITLE
Registrar ID not returned for GoDaddy

### ISSUE THREAD

**Issue by jwineman** [weppos/whois#547]
I'm willing to fix this but I wanted to open an issue to check my approach before doing so.

https://github.com/weppos/whois/blob/master-3.x/lib/whois/record/parser/base_verisign.rb#L72

The code expects the Registrar ID to be in a field called "Sponsoring Registrar IANA ID" but GoDaddy returns "Registrar IANA ID".  Is this the only spot in the code that needs to be updated?  Are there other examples in the code base where we check for field names by multiple names that I can mimic?

**Comment by weppos** [comment]
@jwineman the parser has been moved to https://github.com/weppos/whois-parser. Do you mind to continue the discussion there?

**Comment by jwineman** [comment]
No problem.
