### ISSUE TITLE
Prioritize exp. dates of the registry

### ISSUE THREAD

**Issue by dare05** [weppos/whois#548]
I'm getting a lot of false positives for .com domains that expired, say, 3 days ago, where the registrar whois database says their expiration date is 2017-x-x, while going to Verisign whois, it correctly displays the 2018 expiration date.

I think it is a good idea for the registrar expiration information to NOT overwrite the registry exp. information, in case the registry info is further in the future. Or at least provide an option for this, so I don't have to resort to a hack like clearing the existing definition, and then adding a new definition without an adapter.

**Comment by weppos** [comment]
@dare05 that's challenging. The registrar is the one responsible for the domain, hence they should have the most valid records.

I'm not very inclined to change the approach. I'd report the issue to the registrar, as I don't see any reason they should report stale data after 3 days.
