### ISSUE TITLE
parser.technical_contact example in README fails

### ISSUE THREAD

**Issue by sampablokuper** [weppos/whois#549]
Following the instructions in [README.md](https://github.com/weppos/whois/blob/master/README.md) fails at the step `tech = parser.technical_contact` . This step yields the following error:

```
NoMethodError: undefined method `technical_contact' for #<Whois::Parser:0x00000001d45b88>
	from /home/sampablokuper/.rvm/gems/ruby-2.3.3/gems/whois-parser-1.0.0/lib/whois/parser.rb:338:in `method_missing'
	from (irb):13
	from /home/sampablokuper/.rvm/rubies/ruby-2.3.3/bin/irb:11:in `<main>'

```

I am not sure if this is due to a bug in the README, a bug in `whois-parser`, or something else.

**Comment by sampablokuper** [comment]
Executing `tech = parser.technical_contacts` (note the 's' on the end) gives some progress, but then the following step in the README fails:

```
2.3.3 :015 > tech = parser.technical_contacts
 => [#<struct Whois::Parser::Contact id=nil, type=3, name="Google Ireland Holdings", organization="Google Ireland Holdings", address="70 Sir John Rogersons Quay", city="Dublin", zip="2", state="IE", country=nil, country_code="IE", phone=nil, fax=nil, email=nil, url=nil, created_on=2013-04-21 01:05:35 +0100, updated_on=2013-04-21 01:05:35 +0100>] 
2.3.3 :016 > tech.id
NoMethodError: undefined method `id' for #<Array:0x00000001ba23a8>
	from (irb):16
	from /home/sampablokuper/.rvm/rubies/ruby-2.3.3/bin/irb:11:in `<main>'
```

**Comment by weppos** [comment]
tech = parser.technical_contacts

returns an array, and you can't call `.id` on an array. You will have to use

    tech = parser.technical_contacts.first
    tech.id

**Comment by sampablokuper** [comment]
Thanks :)

Based on your reply, this issue amounts to a bug in the README (cf. my opening comment). As that has not yet been fixed, please can you reopen this issue?

**Comment by sampablokuper** [comment]
I have now submitted a PR. If it solves the problem, then please accept it and re-close this issue.

Thanks again!
