### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by sampablokuper** [weppos/whois#550]
Here is an excerpt from the documentation page at https://whoisrb.org/docs/v3/parser/ :

> [Here's](https://whoisrb.org/manual/parser/properties/) the full list of available properties.

Unfortunately, that link gets redirected to https://whoisrb.org/docs/v3/parse-properties/ which produces:

> 404 Not Found
> 
> * Code: NoSuchKey
> * Message: The specified key does not exist.
> * Key: docs/v3/parse-properties/index.html
> * RequestId: 2F8132094F4D789F
> * HostId: QSO+SB82cRtt8S+PFchQ04/ylVCDKAh0xV2qw7rmX6MSekiOkZuv9CfNlYAEoLJ43PS0mfR8jYc=

P.S. Thank you for all the work that has gone into Ruby Whois, and for publishing it as free software. It's an incredible effort!

**Comment by weppos** [comment]
I fixed the link. Thanks for reporting it!
