### ISSUE TITLE
Make valid_ipv4? and valid_ipv6? in class Server public

### ISSUE THREAD

**Issue by comschmid** [weppos/whois#551]
I'm creating a Java bridge to your library using JRuby and realized that these two methods should be public, since they are used by at least the following two parsers:
* whois.nic.ch.rb
* base_nic_fr.rb

I'm a Ruby beginner, but after I made these two methods public (moving up before private), these parsers work without throwing an Exception.

Thanks,
Stephan

**Comment by weppos** [comment]
Can you provide me a code example to reproduce the error, and some details about the error and the jRuby version?

**Comment by comschmid** [comment]
It actually happens when retrieving the three properties from `parser.nameservers`.
The Exception message is:
> private method `valid_ipv4?' called for Whois::Server:Class Did you mean? valid_ipv6?

For example:
In whois.nic.ch.rb on line 96 is written: `list[name].ipv4 = ip if Whois::Server.valid_ipv4?(ip)`,
but the corresponding method in server.rb on line 361 is private, after it's declaration on line 329.

I'm using the latest JRuby version 9.1.7.0 by using the `org.jruby.embed.ScriptingContainer`.

Previously I used your 3.x version, now I'm upgrading to 4.x. 

Unfortunately I'm also struggling with some weird type conversion errors and the corresponding error messages are mostly not very helpful. E.g. when expecting a Time type (Java: RubyTime) but the variable is nil, suddenly the type for JRuby is of type String (RubyString). This is price to pay when bridging a dynamically typed language with a static one. Any pointer to a page with best practices about type conversion between these two languages would be very helpful!

**Comment by weppos** [comment]
Thanks for the info. AFAIK the lib works fine on 9.1.5.0
https://travis-ci.org/weppos/whois

But it's also possible there are no tests to stress that section. I need to investigate. I won't be able to do it right now, but I expect to be able to work on it in a week.

**Comment by comschmid** [comment]
Thanks for your feedback and your wonderful library!

After making these two methods in class Server public, it works perfectly for me. 
I also managed to circumvent some nasty type conversion problems, simply by analyzing the actual (J)Ruby type and casting or converting appropriately. Not really nice, but it works.

**Comment by comschmid** [comment]
FYI: I just migrated to 9.1.8.0 and updated all referenced gems to the latest versions: all previous findings stay the same.

**Comment by comschmid** [comment]
FYI: with JRuby version 9.1.15.0 no private/public code adaptions are needed anymore.

**Comment by weppos** [comment]
Thanks @comschmid
