### ISSUE TITLE
Testing whois gem in an application

### ISSUE THREAD

**Issue by TheHodge** [weppos/whois#553]
Hello, Is it possible to feed the whois gem a static file (rather than a URL) of the whois response for testing  purposes, it's more for our application than the gem itself, I need to be able to handle situations such as people putting in .com.au domains which have no expiration date or .gov domains which give no information at all

**Comment by weppos** [comment]
This example may help you
https://github.com/weppos/whois/issues/546#issuecomment-273357109
You can construct a Record reading the data from somewhere. Note that you will have to provide to the Part the appropriate host.
