### ISSUE TITLE
Unknown status: 'Deactivated' + 'Reserved'

### ISSUE THREAD

**Issue by AndersDK12** [weppos/whois#555]
Hi, first of all great API, thanks for your work!

I've been getting this error for certain domains which status is "deactivated" or "reserved".

Here's some domains you can use for checking:
"reserved": kreditkortonline.dk
"deactivated": netborder.dk

Thanks again.

**Comment by weppos** [comment]
Hello @AndersDK12 , can you please open the issue at https://github.com/weppos/whois-parser
