### ISSUE TITLE
Not pulling registrar data for .org domains

### ISSUE THREAD

**Issue by darkogj** [weppos/whois#557]
It seems that, for .org domains, there's data being pulled only at registry level (not at registrar level). This is all well and good, however, the problem is: The .org registry is not always in sync with the registrar data b) You can't get the fact if a domain name is expired, because it very often happens that the registrar renews the name on itself (so the registry displays that date), while, at the registrar level, you won't see this fact.

In most user scenarios, I believe, the important fact is to see whether the user OWNING the domain renewed, not what the registrar is doing in the background.

Is there a way to handle this issue? Is there a separate list inside the whois gem where it's being set up so no data is being pulled at a registrar level?

**Comment by weppos** [comment]
The .ORG is not a thin WHOIS server, therefore you are not expected to contact the registry.

In fact, the registrar whois server is not even listed in most cases.

```
Domain Name: GOOGLE.ORG
Registry Domain ID: D2244233-LROR
Registrar WHOIS Server:
Registrar URL: http://www.markmonitor.com
```
