### ISSUE TITLE
Defining servers by symbol does not work

### ISSUE THREAD

**Issue by samnissen** [weppos/whois#564]
Defining servers by symbols do not work in v4, where defining by calling the constant does.

```ruby
2.4.0 :001 > Whois::Server.define :tld, ".com", "whois.name.com"
 => [".com", "whois.name.com", {}]
2.4.0 :002 > Whois::Server.definitions(:tld).map{|s| s if s[0] == "com"}.compact
 => [["com", "whois.verisign-grs.com", {:adapter=>"verisign"}]]
2.4.0 :003 > @client = Whois::Client.new(:timeout => 10)
 => #<Whois::Client:0x007f8a0d83a290 @timeout=10, @settings={}>
2.4.0 :004 > results = @client.lookup("stackoverflow.com")
 => "   Domain Name: STACKOVERFLOW.COM\r\n " # truncated ...
2.4.0 :005 > results.parser.record.server
 => #<Whois::Server::Adapters::Verisign:0x007f8a0b0290f8 @type=:tld, @allocation="com", @host="whois.verisign-grs.com", @options={}, @buffer=[]>
```

```ruby
2.4.0 :001 > Whois::Server.define(Whois::Server::TYPE_TLD, "com", "whois.name.com")
 => ["com", "whois.name.com", {}]
2.4.0 :002 > Whois::Server.definitions(:tld).map{|s| s if s[0] == "com"}.compact
 => [["com", "whois.name.com", {}]]
2.4.0 :003 > @client = Whois::Client.new(:timeout => 10)
 => #<Whois::Client:0x007f8a0b09dca0 @timeout=10, @settings={}>
2.4.0 :004 > results = @client.lookup("stackoverflow.com")
 => "   Domain Name: STACKOVERFLOW.COM\r\n " # truncated ...
2.4.0 :005 > results.parser.record.server
 => #<Whois::Server::Adapters::Standard:0x007f8a0ba127b8 @type=:tld, @allocation="com", @host="whois.name.com", @options={}, @buffer=[]>
```

I'm working off the v3 docs since the v4 docs don't cover this, so I'm not sure if this is expected behavior or not.

**Comment by weppos** [comment]
It's not the constant. Your first code fragment is incorrect as you use `.com`, instead of `com`.

Also note that overrriding the .COM server is not a very good idea. .COM is a thin registry, name.com is the registrar and you should not replace Verisign.

**Comment by samnissen** [comment]
Ah, thank you @weppos -- that makes sense. Sorry for the erroneous bug!

I'm considering this only because Verisign is returning a subset of the record held by the registrar (specifically: no contact details). Is there a way, without overwriting .COM, that will return the details held by the registrar? (Please feel free to [answer this on SO](https://stackoverflow.com/questions/46711602/ruby-whois-gem-doesnt-use-whois-info) for the rep.) I'm obviously out of my depth here, so any help is greatly appreciated!

**Comment by weppos** [comment]
.COM is a thin whois system. That is, you first contact Verisign, the whois response you obtain contains the host of the next whois server you have to query.

As a result, the final whois response is a combination of the response from 2 servers.

In order to extract ALL the details, you need a parser for each server you obtain a response from. Specifically, Verisign and Name.com in your case.

The library has a Verisign parser, but has no Name.com parser. Therefore, it's not able to pull the details from the response coming from Name.com
https://github.com/weppos/whois-parser/tree/master/lib/whois/parsers

You can define a specific parser for Name.com, and the library will attempt to fetch the details from it. Examples are Enom.com and GoDaddy.com parsers:
https://github.com/weppos/whois-parser/blob/master/lib/whois/parsers/whois.enom.com.rb

**Comment by samnissen** [comment]
Thanks as always, @weppos. I understand the need for a parser-per-server. The part I'm more at odds with is upstream.

whois (at least sometimes) knows the registrar server of a given domain (seemingly all registered .com domains). I guess I am suggesting two fetching changes. (My approach to this feature request is all backward I realize -- sorry about that.)

- Add the parsing of the "Registrar WHOIS Server" node anywhere it is returned.
```ruby
client = Whois::Client.new(:timeout => 10)
result = client.lookup("stackoverflow.com")
result.parser.registrar.server 
 => "whois.name.com"
```
- If there is a result for the domain at that node, automatically fetch the whois details at that server, and add it to the parser results. (Parsing of the string to key/value pairs should be an optional next step based on available parsers.)
```ruby
client = Whois::Client.new(:timeout => 10)
result = client.lookup("stackoverflow.com")
result.parser
 => #<Whois::Parser:0x007fef0f8bdca0 @record="   Domain Name: STACKOVERFLOW.COM\r\n
# truncated
result.parser.registrar.results.parser
 => #<Whois::Parser:0x007fef0e0e49f8 @record="Domain Name: STACKOVERFLOW.COM \n 
# truncated; resulting from lookup of domain at whois.name.com ..."
```

The data and abilities are all there for this to happen within the gems, and the gems handling it would be better than [overwriting TLD servers (which is how I'm currently handling this)](https://gist.github.com/samnissen/12962b78df0404cf774a89a94f792085), as you have said. LMK if you'd like me to record these in separate Github issues.


------


As a P.S. is the base registrar parser buggy? I only get name back from the `.registrar` calls for .com and .net results, and all other nodes are nil even though the data is present in the raw record.

```ruby
client = Whois::Client.new(:timeout => 30)
results = client.lookup("stackoverflow.com")
results.parser.registrar
 => #<struct Whois::Parser::Registrar id=nil, name="Name.com, Inc.", organization=nil, url=nil>
results = client.lookup("daringfireball.net")
results.parser.registrar
 => #<struct Whois::Parser::Registrar id=nil, name="Pair Networks Inc.d/b/a pairNIC", organization=nil, url=nil>
results = client.lookup("facebook.com")
results.parser.registrar
 => #<struct Whois::Parser::Registrar id=nil, name="MarkMonitor Inc.", organization=nil, url=nil>
```

**Comment by weppos** [comment]
@samnissen what I'm saying is that the feature is already built-in into the library. If you define a server for name.com, the library will fetch the details from it and merge them with the ones from Verisign.

> As a P.S. is the base registrar parser buggy? I only get name back from the .registrar calls for .com and .net results, and all other nodes are nil even though the data is present in the raw record.

Please make sure to use the latest parser version.

```
2.3.3 :001 > client = Whois::Client.new(:timeout => 30)
 => #<Whois::Client:0x007f88ec25a4f0 @timeout=30, @settings={}>
2.3.3 :002 > results = client.lookup("facebook.com")
2.3.3 :003 > results.parser.registrar
 => #<struct Whois::Parser::Registrar id="292", name="MarkMonitor, Inc.", organization="MarkMonitor, Inc.", url="http://www.markmonitor.com">
```

**Comment by samnissen** [comment]
@weppos Your continued support is much appreciated.

I don't understand what you're implying -- could you provide a code example of how one defines servers on a per-registrar basis? For an example, what would I have to enable for the results of a `lookup` of "stackoverflow.com" to return the payload from whois.name.com ?

**Comment by weppos** [comment]
https://github.com/weppos/whois-parser/blob/master/lib/whois/parsers/whois.enom.com.rb
https://github.com/weppos/whois-parser/blob/master/lib/whois/parsers/whois.godaddy.com.rb

There must be one also for `whois.name.com`, that understands the responses returned by this server.

**Comment by samnissen** [comment]
Just to make sure I'm understanding this correctly: If a parser existed for whois.name.com in the whois-parser gem source, the whois gem would fetch and merge(??) the whois.name.com details with the registry's details upon `lookup` of a domain whose registrar is name.com?

In terms of the gem as-is: Is there a canonical way to define these in programmatically, or is the only way via pull request?

**Comment by weppos** [comment]
> If a parser existed for whois.name.com in the whois-parser gem source, the whois gem would fetch and merge(??) the whois.name.com details with the registry's details upon lookup of a domain whose registrar is name.com?

Correct.

> In terms of the gem as-is: Is there a canonical way to define these in programmatically, or is the only way via pull request?

If you define a class with such naming, in the Ruby namespace, it will be picked up. Ideally, if the class is complete I can package and release it with the lib itself.

**Comment by samnissen** [comment]
OK, sorry it took me so long to understand how this works, but, again, I really appreciate the support!

I am not sure yet if my use case means that I will have to continue to programmatically surface out the server (as I am doing in the gist linked above) or if I can narrow down a handful of new classes to define that will cover most of the domains I need to check. Of course if I solve with new classes, I will pop them in a PR.
