### ISSUE TITLE
how to lookup against one specific server?

### ISSUE THREAD

**Issue by blysik** [weppos/whois#565]
We have a custom whois server, which I use via:

whois -h customwhois.company.com 12.345.456

How can I make a whois request with this gem, and ONLY query that custom whois server, for the request?

Thanks!

**Comment by blysik** [comment]
Whoops, sorry, missed:

# @option settings [String, nil] :host (nil)
    #         The server host to query. Leave it blank for intelligent detection.

**Comment by weppos** [comment]
👍 

Just keep in mind there is a small bug that may affect you: #440
