### ISSUE TITLE
How to specify whois server for request?

### ISSUE THREAD

**Issue by hxhxd** [weppos/whois#573]
Hi, I've tried many times, seems it's not working:
`client = Whois::Client.new(host: 'whois.crsnic.net', bind_host: ips[count % ipl])`
or 
`Whois::Server.define :tld, ".com", "whois.crsnic.net"`

But still I got error message:
`"Errno::ECONNREFUSED: Connection refused - connect(2) for \"whois.bizcn.com\" port 43"`

Is there a workaround for this? Like I build a server/adapter and pass it to client or so?
Thanks!

**Comment by weppos** [comment]
`whois.bizcn.com` is not set anywhere, not even in the TLD definition. Therefore, it's likely to have some code that manipulates/overrides the host somewhere and it's causing the conflict.

```
client = Whois::Client.new(host: '...')
client.lookup("example.com")
```

is the correct way to use a specific host as server.

**Comment by hxhxd** [comment]
Thanks for reply.  
`client = Whois::Client.new(host: '...')`
is the way I tried first. Yet it seems not working somehow.

My system is Freebsd 9, with ruby 2.4 and whois 4.0.6.

**Comment by weppos** [comment]
You need to find what code is currently conflicting as the host is being overridden somewhere in your code introducing a host that I don't recognize.
