### ISSUE TITLE
.io parser is broken

### ISSUE THREAD

**Issue by ddmud** [weppos/whois#578]
For google.io the raw response I get is:

`Domain Name: GOOGLE.IO\r\nRegistry Domain ID: D503300000040517313-LRMS\r\nRegistrar WHOIS Server: whois.markmonitor.com\r\nRegistrar URL: http://www.markmonitor.com\r\nUpdated Date: 2018-08-29T09:39:05Z\r\nCreation Date: 2002-10-01T01:00:00Z\r\nRegistry Expiry Date: 2019-09-30T01:00:00Z\r\nRegistrar Registration Expiration Date:\r\nRegistrar: MarkMonitor Inc.\r\nRegistrar IANA ID: 292\r\nRegistrar Abuse Contact Email: abusecomplaints@markmonitor.com\r\nRegistrar Abuse Contact Phone: +1.2083895740\r\nReseller:\r\nDomain Status: clientDeleteProhibited https://icann.org/epp#clientDeleteProhibited\r\nDomain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited\r\nDomain Status: clientUpdateProhibited https://icann.org/epp#clientUpdateProhibited\r\nRegistrant Organization: Google Inc.\r\nRegistrant State/Province: CA\r\nRegistrant Country: US\r\nName Server: NS1.GOOGLE.COM\r\nName Server: NS2.GOOGLE.COM\r\nName Server: NS3.GOOGLE.COM\r\nName Server: NS4.GOOGLE.COM\r\nDNSSEC: unsigned\r\n\r\n\u003e\u003e\u003e Last update of WHOIS database: 2019-02-11T22:02:12Z \u003c\u003c\u003c\r\n\r\nFor more information on Whois status codes, please visit https://icann.org/epp\r\n\r\nAccess to WHOIS information provided by Internet Computer Bureau Ltd. (\"ICB\") is provided to assist persons in determining the contents of a domain name registration record in the ICB registry database. The data in this record is provided by ICB for informational purposes only, and ICB does not guarantee its accuracy. This service is intended only for query-based access. You agree that you will use this data only for lawful purposes and that, under no circumstances will you use this data to(i) allow, enable, or otherwise support the transmission by e-mail, telephone, facsimile or other electronic means of mass, unsolicited, commercial advertising or solicitations to entities other than the data recipient's own existing customers; or (ii) enable high volume, automated, electronic processes that send queries or data to the systems of Registry Operator, a Registrar, or ICB or its services providers except as reasonably necessary to register domain names or modify existing registrations. UK privacy laws limit the scope of information permitted for certain public access.  Therefore, concerns regarding abusive use of domain registrations in the ICB registry should be directed to either (a) the Registrar of Record as indicated in the WHOIS output, or (b) the ICB anti-abuse department at abuse@icbregistry.info.\n\nAll rights reserved. ICB reserves the right to modify these terms at any time. By submitting this query, you agree to abide by these policies\n\nThe Registrar of Record identified in this output may have an RDDS service that can be queried for additional information on how to contact the Registrant, Admin, or Tech contact of the queried domain name.\r\n`

Yet, the parsed response results in blank creation, updated and expires dates as well as no nameservers as well as blanks for most everything else.

**Comment by weppos** [comment]
Please report parser issues to https://github.com/weppos/whois-parser.
