### ISSUE TITLE
Using this gem in a commercial setting

### ISSUE THREAD

**Issue by Medvezo** [weppos/whois#581]
Hello!

Are there any legal or technical (e.g. throttling) implications of using this gem in a commercial setting? Do you send queries to _root WHOIS servers_ (is this even a thing?) ?  

Even in development, with very low number of API queries, I have been noticing increased rates of `Whois::ConnectionError: Errno::ECONNRESET` and that made me ponder.

Thanks for your work!

**Comment by weppos** [comment]
This library sends request directly to the registrars whois servers. Each TLD have different policy regarding the number of queries you are allowed to perform. Furthermore, each TLD have different agreements.

You will need to check the TLD specific policies at the registries.
