### ISSUE TITLE
Bug with .cat TLD

### ISSUE THREAD

**Issue by The-Nutty** [weppos/whois#583]
Looking up a .cat TLD does not work, for example looking up nyan.cat shows no matching objects found. 

Looking at tld.json 
```
  "cat": {
    "host": "whois.nic.cat",
    "adapter": "formatted",
    "format": "-C US-ASCII ace %s"
  },
```

if you change the format to "-C US-ASCII %s" (just removing ace) it works fine. 

Is there a reason ace is included?

This can be reproduced with the code:

```
require 'whois'

whois = Whois::Client.new
puts whois.lookup("nyan.cat")
```

**Comment by weppos** [comment]
Thanks for reporting it.

I actually removed the entirely use of a formatting adapter. It is no longer necessary.
In fact, querying `nic.cat` with the formatted adapter resulted in `?` in place of the UTF-8 chars. Using the default adapter, that accepts unicode, is able to get the correct result.
