### ISSUE TITLE
whois query for .tv does not return information

### ISSUE THREAD

**Issue by AlexanderMarkevich** [weppos/whois#662]
Hello,
whois request for .tv does not return information (for example, the domain steambeer.tv). 
But if we remove "adapter": "verisign" for "host": "whois.nic.tv" from data/tld.json , then the information will be returned correctly

**Comment by edasque** [comment]
Odd, the interactive web site at https://whois.nic.tv/ returns information for steambeer.tv

So does the unix CLI tool ```whois```:

```
whois -h whois.nic.tv steambeer.tv
Domain Name: steambeer.tv
Registry Domain ID: 86643832_DOMAIN_TV-GDREG
Registrar WHOIS Server: whois.markmonitor.com
Registrar URL: www.markmonitor.com
...
```

I don't know what the adapter is for (I don't use this repo for the Ruby client)

**Comment by weppos** [comment]
Thanks, fixed. The adapter define the behavior of the query. The .TV backed used to be run by Verisign, but the TLD has now moved to GoDaddy Registry backend.
